import test from 'node:test'; import assert from 'node:assert/strict';
import {createDebate,beginNext,recordTurn,completeAudio,submitAudience,pause,resume,stop,STATES,contextFor} from '../lib/debate.mjs';
const input={proposition:'Local models will replace cloud models.',rounds:1,for:{model:'a',voice:'a'},against:{model:'b',voice:'b'},referee:{enabled:true,model:'r',voice:'r'}};
const turn=d=>{beginNext(d);recordTurn(d,{text:'A direct response.',model:'x',provider:'mock'});completeAudio(d)};
test('orders a referee debate and preserves positions',()=>{let d=createDebate(input);turn(d);assert.equal(d.state,STATES.FOR_OPENING);turn(d);assert.equal(d.state,STATES.AGAINST_OPENING);turn(d);assert.equal(d.state,STATES.FOR_REBUTTAL);turn(d);assert.equal(d.state,STATES.AGAINST_REBUTTAL);turn(d);assert.equal(d.state,STATES.REFEREE_INTERVENTION);assert.equal(d.transcript[1].speaker,'for');assert.equal(d.transcript[2].speaker,'against');});
test('audience intervention safely interrupts and reaches both debaters',()=>{let d=createDebate(input);turn(d);submitAudience(d,'What about privacy?');let c=beginNext(d);assert.equal(c.state,STATES.AUDIENCE_INTERVENTION);assert.match(contextFor(d,'referee').audience,/privacy/);recordTurn(d,{text:'Noted.',model:'r',provider:'mock'});completeAudio(d);assert.equal(d.state,STATES.FOR_OPENING);beginNext(d);assert.match(contextFor(d,'for').audience,/privacy/);recordTurn(d,{text:'For reply',model:'a',provider:'mock'});completeAudio(d);beginNext(d);assert.match(contextFor(d,'against').audience,/privacy/);recordTurn(d,{text:'Against reply',model:'b',provider:'mock'});assert.equal(d.activeAudience,null);});
test('pause resume and stop reject invalid advancement',()=>{let d=createDebate(input);pause(d);assert.equal(d.state,STATES.PAUSED);resume(d);assert.equal(d.state,STATES.READY);stop(d);assert.equal(d.state,STATES.STOPPED);assert.throws(()=>beginNext(d),/ended/);});
test('context includes recent opponent but bounds history',()=>{let d=createDebate(input);for(let i=0;i<8;i++)d.transcript.push({speaker:i%2?'against':'for',text:`turn${i}`});let c=contextFor(d,'for');assert.match(c.opponent,/turn7/);assert.doesNotMatch(c.recent,/turn0/);});
test('rejects reused participant voices',()=>assert.throws(()=>createDebate({...input,against:{model:'b',voice:'a'}}),/distinct voices/));
