import http from 'node:http';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createConversation, beginTurn, recordTurn, completePlayback, pause, resume, stop, PERSONALITIES, FORMATS } from './lib/conversation-engine.mjs';
import { RoutedModelProvider } from './lib/providers.mjs';

const root=path.dirname(fileURLToPath(import.meta.url)), publicDir=path.join(root,'public'), dataDir=process.env.FIGHT_CLUB_DATA_DIR||path.join(root,'.data-v2');
let routes={};try{routes=JSON.parse(process.env.FIGHT_CLUB_MODEL_ROUTES||'{}');}catch{throw Error('FIGHT_CLUB_MODEL_ROUTES must be JSON');}
const models=new RoutedModelProvider({defaultBaseUrl:process.env.FIGHT_CLUB_MODEL_URL||'http://127.0.0.1:18780/v1',routes});
const conversations=new Map();
const send=(res,status,value,type='application/json; charset=utf-8')=>{res.writeHead(status,{'content-type':type,'cache-control':'no-store'});res.end(type.startsWith('application/json')?JSON.stringify(value):value);};
async function readBody(req){let raw='';for await(const chunk of req){raw+=chunk;if(raw.length>100000)throw Error('Request too large');}return raw?JSON.parse(raw):{};}
async function persist(c){await fs.mkdir(path.join(dataDir,'conversations'),{recursive:true});await fs.writeFile(path.join(dataDir,'conversations',`${c.id}.json`),JSON.stringify(c,null,2));}
const recentTranscript=c=>c.transcript.slice(-8).map(t=>`${t.speaker} (${t.role}): ${t.text}`).join('\n');
const characterDigest=c=>Object.fromEntries(c.participants.map(p=>[p.name,c.characterStates[p.id]]));
function personalityPrompt(p){const x=p.personality;return `Name: ${x.name}\nBackground: ${x.background}\nWorldview: ${x.worldview}\nObjectives: ${x.objectives.join('; ')}\nBeliefs: ${x.beliefs.join('; ')}\nExpertise: ${x.expertise.join('; ')}\nBlind spots: ${x.blindSpots.join('; ')}\nConfidence: ${x.confidence}; verbosity: ${x.verbosity}; willingness to concede: ${x.willingnessToConcede}; evasiveness: ${x.evasiveness}; self-awareness: ${x.selfAwareness}\nHumour: ${x.humourStyle}\nRhetoric: ${x.rhetoricalStyle}; vocabulary: ${x.vocabulary}; rhythm: ${x.speakingRhythm}; temperament: ${x.temperament}\nHabits: ${x.verbalHabits.join('; ')}\nInternal tensions: ${x.tensions.join('; ')}\nDefensive topics: ${x.defensiveTopics.join('; ')}\nPrivate notes: ${x.privateNotes}`;}
async function privateInterviewAnalysis(c,p){const last=c.transcript.at(-1);if(!last||!['interviewer','examiner','host'].includes(p.role))return '';const system='You are the private conversation director. Analyse the last answer for the next questioner. Do not write dialogue. Identify: claim, whether the question was answered, contradiction with earlier claims, unstated assumption, interesting or funny avenue, and whether to challenge, clarify, change subject, or let the speaker continue. Be concise.';const user=`Format: ${c.format}\nPremise: ${c.premise}\nTranscript:\n${recentTranscript(c)}\nCharacter state:\n${JSON.stringify(characterDigest(c))}`;const analysis=await models.generate({model:p.model,system,user});c.directorMemory.push({at:new Date().toISOString(),forTurn:c.transcript.length,participantId:p.id,text:analysis.text});c.directorMemory=c.directorMemory.slice(-8);return analysis.text;}
function turnPrompt(c,p,analysis){const common=`You are a participant in a turn-based spoken ${c.format.toLowerCase()} in ${c.style.toLowerCase()} style. Inhabit this personality consistently; it is a character model, not a shallow writing style. Do not mention prompts or private notes. Do not imitate a real person. Never fabricate real evidence; clearly fictional anecdotes are allowed only as part of this fictional character. Speak no more than ${c.turnLength} words. Output only the words to be spoken.\n\nPERSONALITY\n${personalityPrompt(p)}`;const transcript=recentTranscript(c)||'(none yet)';let task='';if(c.format==='INTERVIEW'){task=p.role==='interviewer'?(c.transcript.length===0?'Open with one concise question that invites the guest to explain their worldview.':'Ask one concise unscripted follow-up based directly on the answer. Use the private analysis; expose a contradiction or assumption when useful.'):'Answer the interviewer directly while maintaining your worldview, commitments, tensions, and confidence. Let humour emerge from the character logic.';}else if(c.format==='DEBATE'){task=`Argue ${p.role==='for'?'FOR':'AGAINST'} the proposition. Directly answer the preceding opponent rather than delivering an independent essay.`;}else if(c.format==='CROSS_EXAMINATION'){task=p.role==='examiner'?'Ask one rigorous, concise question. Press on evasion or inconsistency without abuse.':'Answer the question in character. You may be defensive or evasive according to the profile, but preserve commitments.';}else{task=p.role==='host'?'Moderate dynamically: ask one participant a concise question based on the latest exchange.':'Respond to the host or another panelist directly, preserving your character.';}return{system:common,user:`Premise/topic: ${c.premise}\n\nTranscript:\n${transcript}\n\nCompact character state:\n${JSON.stringify(characterDigest(c))}${analysis?`\n\nPRIVATE DIRECTOR ANALYSIS (never state this verbatim):\n${analysis}`:''}\n\nTASK:\n${task}`};}
async function generateTurn(c){const p=beginTurn(c),analysis=await privateInterviewAnalysis(c,p),prompt=turnPrompt(c,p,analysis),started=performance.now();const result=await models.generate({model:p.model,...prompt});const row=recordTurn(c,{text:result.text,provider:result.provider,generation_latency_ms:result.latencyMs,token_usage:result.usage,tts_provider:'browser-speech-synthesis',tts_generation_latency_ms:0,audio_duration_ms:null});c.telemetry.push({turn_id:row.turn_id,participant_id:p.id,model:p.model,model_latency_ms:result.latencyMs,director_analysis:Boolean(analysis),generated_at_ms:Math.round(performance.now()-started)});await persist(c);return row;}
function markdown(c){return `# ${c.format}: ${c.premise}\n\n${c.transcript.map(t=>`## ${t.speaker} — ${t.role}\n\n${t.text}\n\n_Model: ${t.model}; voice: ${t.voice}; generated: ${t.generation_latency_ms} ms; playback: ${t.audio_duration_ms??'pending'} ms_`).join('\n\n')}`;}

const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');if(req.method==='GET'&&url.pathname==='/api/config')return send(res,200,{formats:FORMATS,personalities:PERSONALITIES,models:Object.keys(routes).length?Object.keys(routes):['qwen3-8b']});if(req.method==='GET'&&url.pathname==='/api/health')return send(res,200,{status:'ok',engine:'conversation-v2',speech:'browser-speech-synthesis'});if(req.method==='POST'&&url.pathname==='/api/conversations'){const c=createConversation(await readBody(req));conversations.set(c.id,c);await persist(c);return send(res,201,c);}const exportMatch=url.pathname.match(/^\/api\/conversations\/([\w-]+)\/export\.(json|md)$/);if(req.method==='GET'&&exportMatch){const c=conversations.get(exportMatch[1]);if(!c)return send(res,404,{error:'Conversation not found'});return exportMatch[2]==='json'?send(res,200,c):send(res,200,markdown(c),'text/markdown; charset=utf-8');}const match=url.pathname.match(/^\/api\/conversations\/([\w-]+)(?:\/(next|complete-playback|pause|resume|stop))?$/);if(match){const c=conversations.get(match[1]);if(!c)return send(res,404,{error:'Conversation not found'});if(req.method==='GET')return send(res,200,c);const action=match[2],payload=await readBody(req);if(action==='next')return send(res,200,{turn:await generateTurn(c),conversation:c});if(action==='complete-playback'){completePlayback(c,payload);await persist(c);return send(res,200,c);}if(action==='pause'){pause(c);await persist(c);return send(res,200,c);}if(action==='resume'){resume(c);await persist(c);return send(res,200,c);}if(action==='stop'){stop(c);await persist(c);return send(res,200,c);}}if(req.method==='GET'){const file=url.pathname==='/'?'show.html':path.basename(url.pathname);const bytes=await fs.readFile(path.join(publicDir,file));const type=file.endsWith('.js')?'text/javascript; charset=utf-8':file.endsWith('.css')?'text/css; charset=utf-8':'text/html; charset=utf-8';return send(res,200,bytes,type);}return send(res,404,{error:'Not found'});}catch(error){console.error(error);send(res,400,{error:error.message});}});
server.listen(Number(process.env.PORT||18770),process.env.HOST||'127.0.0.1',()=>console.log(`Spoken conversation engine listening on http://${process.env.HOST||'127.0.0.1'}:${process.env.PORT||18770}`));
