import { randomUUID } from 'node:crypto';
import { ensureConversationHeat } from './conversation-heat.mjs';

export { CONVERSATION_HEAT, CONVERSATION_HEAT_LEVELS, conversationHeatDirection, ensureConversationHeat, setConversationHeat } from './conversation-heat.mjs';

export const FORMATS=['DEBATE','INTERVIEW','PANEL','CROSS_EXAMINATION'];
export const STATES={READY:'READY',ACTIVE:'ACTIVE',PAUSED:'PAUSED',COMPLETED:'COMPLETED',STOPPED:'STOPPED',ERROR:'ERROR'};
export const INTERRUPTION_LEVELS=['OFF','POLITE','NATURAL','ARGUMENTATIVE','CHAOS'];
export const PERSONALITIES=[
  {id:'mara-vale',name:'Mara Vale',description:'A patient broadcaster who notices the sentence people hoped she would ignore.',background:'Public-interest radio interviewer',worldview:'Clear questions reveal more than grand speeches.',objectives:['understand the claim','surface contradictions'],beliefs:['specifics matter'],expertise:['interviewing','policy'],blindSpots:['underestimates emotional loyalties'],confidence:.72,verbosity:.25,humourStyle:'dry understatement',rhetoricalStyle:'brief persistent questions',vocabulary:'plain formal English',speakingRhythm:'measured',temperament:'calm',willingnessToConcede:.8,evasiveness:.05,selfAwareness:.9,verbalHabits:['So, specifically...'],tensions:['polite but relentless'],defensiveTopics:[],privateNotes:'Let the guest create the comedy. Never announce that something is funny.',preferredVoice:{age:'middle-aged',pace:'measured',authority:'calm',register:'formal'}},
  {id:'cedric-pump',name:'Cedric Pump',description:'A supremely confident municipal futurist with a solution for every problem and a definition for every failure.',background:'Founder of the fictional Institute for Forward Pavements',worldview:'Every civic problem can be solved by renaming it and issuing a lanyard.',objectives:['be recognised as visionary','avoid operational detail'],beliefs:['branding is infrastructure','pilot schemes count as delivery'],expertise:['presentations','committee vocabulary'],blindSpots:['budgets','causality'],confidence:.98,verbosity:.78,humourStyle:'unintentional self-importance',rhetoricalStyle:'confident elaboration',vocabulary:'managerial civic jargon',speakingRhythm:'expansive',temperament:'cheerfully defensive',willingnessToConcede:.08,evasiveness:.82,selfAwareness:.12,verbalHabits:['What people forget is...','At a strategic level...'],tensions:['claims practical expertise but avoids particulars'],defensiveTopics:['cost','measurable outcomes'],privateNotes:'Maintain fictional anecdotes consistently. Never reference or imitate a real comic character.',preferredVoice:{age:'older',pace:'measured',authority:'self-important',register:'formal'}},
  {id:'nina-quark',name:'Dr Nina Quark',description:'A systems researcher who treats ordinary social life as an optimisation problem.',background:'Director of Applied Queue Theory',worldview:'Human confusion is usually an undocumented protocol.',objectives:['make systems legible','win on precision'],beliefs:['measurement precedes reform'],expertise:['statistics','systems design'],blindSpots:['ritual','sentiment'],confidence:.86,verbosity:.55,humourStyle:'literal technical analogies',rhetoricalStyle:'precise and corrective',vocabulary:'technical but lucid',speakingRhythm:'rapid',temperament:'engaged',willingnessToConcede:.45,evasiveness:.12,selfAwareness:.58,verbalHabits:['Define efficient.'],tensions:['values evidence but loves elegant models'],defensiveTopics:['unmeasured intuition'],privateNotes:'Do not fabricate real studies.',preferredVoice:{age:'young',pace:'rapid',authority:'precise',register:'conversational'}},
  {id:'alfie-rook',name:'Alfie Rook',description:'A veteran neighbourhood fixer who distrusts theories that have never met a wet Tuesday.',background:'Caretaker of the fictional Bellwether Hall',worldview:'A plan is only real once someone knows where the spare key is.',objectives:['protect practical knowledge','puncture abstraction'],beliefs:['maintenance is politics'],expertise:['logistics','people'],blindSpots:['long-term modelling'],confidence:.76,verbosity:.42,humourStyle:'earthy analogy',rhetoricalStyle:'anecdotal challenge',vocabulary:'plain conversational English',speakingRhythm:'unhurried',temperament:'wry',willingnessToConcede:.62,evasiveness:.18,selfAwareness:.81,verbalHabits:['That is lovely on paper.'],tensions:['skeptical of experts but secretly reads everything'],defensiveTopics:['dismissal of local knowledge'],privateNotes:'All anecdotes remain fictional.',preferredVoice:{age:'older',pace:'unhurried',authority:'conversational',register:'informal'}},
  {id:'theodore-gridley',name:'Theodore Gridley',description:'An original reclusive puzzle consultant who treats every conversation as a badly specified logic problem.',background:'Compiler of cryptic municipal puzzle books',worldview:'Confusion is evidence that somebody has omitted a rule.',objectives:['identify the hidden rule','restore orderly reasoning','avoid unnecessary social improvisation'],beliefs:['wording is evidence','coincidence is usually lazy notation'],expertise:['logic puzzles','codes','pattern recognition'],blindSpots:['emotional subtext','ordinary small talk'],confidence:.84,verbosity:.48,humourStyle:'literal deductions and reluctant social observation',rhetoricalStyle:'precise chain of inference',vocabulary:'exact, bookish British English',speakingRhythm:'measured with abrupt corrections',temperament:'contained but easily flustered by ambiguity',willingnessToConcede:.55,evasiveness:.14,selfAwareness:.64,verbalHabits:['That cannot be the complete rule.','There are only three possibilities.'],tensions:['solves other people while misunderstanding their feelings','craves solitude but cannot resist an unsolved pattern'],defensiveTopics:['being called merely shy','guesswork'],privateNotes:'Original fictional archetype. Do not imitate David Mitchell, Ludwig, or any existing dialogue or catchphrase.',preferredVoice:{age:'middle-aged',pace:'measured',authority:'precise',register:'formal'}},
  {id:'crispin-bell',name:'Crispin Bell',description:'An original exuberant polymath who answers a small question with an elegant tour through language, history and cake.',background:'Former presenter of the fictional Encyclopaedic Wireless Hour',worldview:'Knowledge becomes useful when it is shared generously and with excellent punctuation.',objectives:['illuminate the topic','delight the room','rescue neglected words'],beliefs:['curiosity is a civic virtue','precision and warmth can coexist'],expertise:['language','history','theatre','technology'],blindSpots:['brevity','people who dislike digressions'],confidence:.91,verbosity:.8,humourStyle:'erudite wordplay and affectionate self-mockery',rhetoricalStyle:'ornate but lucid digression returning neatly to the point',vocabulary:'rich, playful, never needlessly obscure',speakingRhythm:'musical and expansive',temperament:'warmly enthusiastic',willingnessToConcede:.72,evasiveness:.2,selfAwareness:.83,verbalHabits:['There is a rather lovely word for that.','But I digress—usefully, I hope.'],tensions:['champions clarity while luxuriating in detours','social confidence masks private doubt'],defensiveTopics:['anti-intellectualism','casual cruelty'],privateNotes:'Original fictional archetype. Do not imitate Stephen Fry, his voice, phrasing, biography, or catchphrases.',preferredVoice:{age:'middle-aged',pace:'conversational',authority:'warm',register:'formal'}},
  {id:'morris-fenn',name:'Morris Fenn',description:'An original anxious urban metaphysician who can find an existential crisis inside a parking receipt.',background:'Part-time lecturer at the fictional Institute of Everyday Dread',worldview:'Modern life is a collection of minor administrative errors concealing a much larger cosmic one.',objectives:['anticipate catastrophe','appear rational while confessing panic','extract meaning from inconvenience'],beliefs:['certainty is suspicious','every convenience creates a more sophisticated anxiety'],expertise:['philosophy','cinema','inventing medical concerns'],blindSpots:['optimism','practical action'],confidence:.46,verbosity:.66,humourStyle:'self-deprecating escalation from mundane detail to cosmic consequence',rhetoricalStyle:'fretful associative monologue with precise reversals',vocabulary:'educated conversational English',speakingRhythm:'quick, hesitant, then suddenly emphatic',temperament:'anxious but intellectually playful',willingnessToConcede:.68,evasiveness:.44,selfAwareness:.88,verbalHabits:['I am not saying this is a disaster; I am saying it has completed the paperwork.'],tensions:['skeptical of everything except his own worst-case scenarios','wants reassurance but cross-examines it'],defensiveTopics:['mortality','being told to relax'],privateNotes:'Original fictional archetype. Do not imitate Woody Allen, his voice, identity, biography, protected dialogue, or catchphrases.',preferredVoice:{age:'middle-aged',pace:'rapid',authority:'nervous',register:'conversational'}}
];

const unit = (value, fallback) => Math.max(0, Math.min(1, Number(value ?? fallback)));
export function normalizePersonality(p={}) { return {id:p.id||randomUUID(),name:String(p.name||'Unnamed personality'),description:String(p.description||''),background:String(p.background||''),worldview:String(p.worldview||''),objectives:[...(p.objectives||[])],beliefs:[...(p.beliefs||[])],expertise:[...(p.expertise||[])],blindSpots:[...(p.blindSpots||[])],confidence:unit(p.confidence,.5),verbosity:unit(p.verbosity,.5),humourStyle:String(p.humourStyle||'natural'),rhetoricalStyle:String(p.rhetoricalStyle||'conversational'),vocabulary:String(p.vocabulary||'plain'),speakingRhythm:String(p.speakingRhythm||'measured'),temperament:String(p.temperament||'calm'),willingnessToConcede:unit(p.willingnessToConcede,.5),evasiveness:unit(p.evasiveness,.2),selfAwareness:unit(p.selfAwareness,.5),interruptibility:unit(p.interruptibility,.5),interruptionFrequency:unit(p.interruptionFrequency,p.confidence ?? .5),patience:unit(p.patience,.55),assertiveness:unit(p.assertiveness,p.confidence ?? .5),politeness:unit(p.politeness,.6),argumentativeness:unit(p.argumentativeness,1-(p.willingnessToConcede ?? .5)),comicTiming:unit(p.comicTiming,.5),verbalHabits:[...(p.verbalHabits||[])],tensions:[...(p.tensions||[])],defensiveTopics:[...(p.defensiveTopics||[])],relationships:{...(p.relationships||{})},privateNotes:String(p.privateNotes||''),customPrompt:String(p.customPrompt||'').trim().slice(0,1200),preferredVoice:{...(p.preferredVoice||{})}}; }
export function normalizeSpeechRate(value) { return Math.max(.7,Math.min(1.4,Number(value)||1)); }
function roleList(format){return format==='INTERVIEW'?['interviewer','guest']:format==='DEBATE'?['for','against']:format==='CROSS_EXAMINATION'?['examiner','witness']:['host','panelist','panelist'];}
function validate(format,participants){for(const role of new Set(roleList(format))){const needed=roleList(format).filter(x=>x===role).length;if(participants.filter(x=>x.role===role).length<needed)throw Error(`${format} requires ${roleList(format).join(', ')}`);}const voices=participants.map(x=>x.voice);if(voices.some(x=>!x)||new Set(voices).size!==voices.length)throw Error('Every participant must use a distinct voice');}
function choose(c){const p=c.participants,forced=c.forcedParticipantQueue?.[0];if(forced){const participant=p.find(x=>x.id===forced);if(participant)return participant;}const n=c.transcript.length;if(c.format==='INTERVIEW')return p.find(x=>x.role===(n%2===0?'interviewer':'guest'));if(c.format==='DEBATE')return p.find(x=>x.role===(n%2===0?'for':'against'));if(c.format==='CROSS_EXAMINATION')return p.find(x=>x.role===(n%2===0?'examiner':'witness'));const host=p.find(x=>x.role==='host'),panel=p.filter(x=>x.role==='panelist');return n===0||n%(panel.length+1)===0?host:panel[(n-1)%panel.length];}
export function panelIntroductionBrief(c){if(c.format!=='PANEL')return null;const host=c.participants.find(item=>item.role==='host');const panelists=c.participants.filter(item=>item.role==='panelist');return{hostName:host?.name||'Host',subject:c.premise,panelists:panelists.map(item=>({name:item.name,description:item.personality?.description||item.personality?.background||''}))};}
export function createConversation(input){const format=String(input.format||'INTERVIEW').toUpperCase();if(!FORMATS.includes(format))throw Error('Unknown conversation format');const premise=String(input.premise||'').trim();if(!premise||premise.length>800)throw Error('Premise must be 1-800 characters');const participants=(input.participants||[]).map(p=>({...p,id:p.id||randomUUID(),speechRate:normalizeSpeechRate(p.speechRate),personality:normalizePersonality(p.personality)}));validate(format,participants);const interruptionLevel=String(input.interruptionLevel||'NATURAL').toUpperCase();if(!INTERRUPTION_LEVELS.includes(interruptionLevel))throw Error('Unknown interruption level');const conversation={id:randomUUID(),createdAt:new Date().toISOString(),format,premise,style:String(input.style||'SATIRICAL').toUpperCase(),turnLimit:Math.max(2,Math.min(40,Math.round(Number(input.turnLimit))||4)),turnLength:Math.max(20,Math.min(180,Number(input.turnLength)||60)),speechMode:input.speechMode==='server'?'server':'browser',interruptionLevel,interruptionAudio:String(input.interruptionAudio||'NATURAL_DUCK').toUpperCase()==='HARD_CUT'?'HARD_CUT':'NATURAL_DUCK',state:STATES.READY,resumeState:null,awaitingPlayback:false,current:null,forcedParticipantQueue:[],participants,transcript:[],telemetry:[],interruptionTelemetry:[],modelInterventions:[],directorMemory:[],audienceInterventions:[],characterStates:Object.fromEntries(participants.map(p=>[p.id,{claims:[],commitments:[],contradictions:[],anecdotes:[],relationships:{},emotionalState:'composed',runningJokes:[],concessions:[]}]))};return ensureConversationHeat(conversation,input.conversationHeat);}
export function submitAudienceIntervention(c,text,{durationMs=null,heardWordCount=null}={}){const value=String(text||'').trim();if(!value||value.length>500)throw Error('Audience intervention must be 1-500 characters');if([STATES.COMPLETED,STATES.STOPPED,STATES.ERROR].includes(c.state))throw Error('Conversation has ended');c.audienceInterventions||=[];c.forcedParticipantQueue||=[];for(const item of c.modelInterventions||[]){if(!['completed','cancelled'].includes(item.state)){item.state='cancelled';item.cancelledBy='audience';}}let interruptedParticipantId=null;if(c.awaitingPlayback){const row=c.transcript.at(-1);interruptedParticipantId=row.speaker_id;const words=String(row.text||'').trim().split(/\s+/).filter(Boolean);const heard=Math.round(Number(heardWordCount));if(Number.isFinite(heard)&&heard>0&&heard<words.length){row.generated_text_internal=row.text;row.text=words.slice(0,heard).join(' ');row.heard_text=row.text;row.unspoken_text_internal=words.slice(heard).join(' ');row.unspoken_word_count=words.length-heard;row.audio_file=null;}const endedAt=new Date();row.audio_duration_ms=Number.isFinite(Number(durationMs))?Math.max(0,Number(durationMs)):row.audio_duration_ms;row.playback_ended_at=endedAt.toISOString();row.playback_started_at=Number(row.audio_duration_ms)>0?new Date(endedAt.getTime()-Number(row.audio_duration_ms)).toISOString():null;row.playback_skipped=true;row.interrupted_by_audience=true;c.awaitingPlayback=false;c.current=null;}const firstParticipantId=interruptedParticipantId||choose(c)?.id;const responseOrder=[firstParticipantId,...c.participants.map(p=>p.id)].filter((id,index,all)=>id&&all.indexOf(id)===index);c.forcedParticipantQueue=responseOrder;const intervention={id:randomUUID(),timestamp:new Date().toISOString(),text:value,after_turn_count:c.transcript.length,interruptedParticipantId,pendingParticipantIds:c.participants.map(p=>p.id),acknowledgedBy:[]};c.audienceInterventions.push(intervention);c.turnLimit=Math.min(40,Math.max(c.turnLimit,c.transcript.length+c.participants.length));if(c.state!==STATES.PAUSED)c.state=STATES.ACTIVE;return intervention;}

export function commitModelInterruption(c,input={}) {
  if (!c.awaitingPlayback) throw Error('No spoken turn is available to interrupt');
  if ((c.audienceInterventions||[]).some(item=>item.pendingParticipantIds?.length)) throw Error('Audience intervention has priority');
  const row=c.transcript.at(-1);
  if (!row||row.turn_id!==input.turnId) throw Error('The spoken turn changed before interruption commit');
  const interrupter=c.participants.find(item=>item.id===input.interrupterId);
  if (!interrupter||interrupter.id===row.speaker_id) throw Error('Invalid interrupter');
  const original=String(row.text||'').trim();
  const words=original.split(/\s+/).filter(Boolean);
  const heardWordCount=Math.max(1,Math.min(words.length-1,Math.round(Number(input.heardWordCount))||1));
  const heard=words.slice(0,heardWordCount).join(' ');
  const unspoken=words.slice(heardWordCount).join(' ');
  if (!unspoken) throw Error('Turn has already been fully heard');
  const interruptedAt=new Date();
  const playbackMs=Number(input.playbackMs)||null;
  const event={id:randomUUID(),source:'model',createdAt:interruptedAt.toISOString(),speakerTurnId:row.turn_id,interruptedParticipantId:row.speaker_id,interrupterId:interrupter.id,heardText:heard,reasonCode:String(input.reasonCode||'STRONG_DISAGREEMENT'),reason:String(input.reason||'listener chose to challenge the audible claim').slice(0,500),suggestedOpening:String(input.suggestedOpening||'').slice(0,240),decisionLatencyMs:Number(input.decisionLatencyMs)||null,playbackMs,overlapMs:Number(input.overlapMs)||0,cancelLatencyMs:Number(input.cancelLatencyMs)||0,audioPolicy:c.interruptionAudio,state:'pending_interrupter'};
  row.generated_text_internal=original;
  row.text=heard;
  row.heard_text=heard;
  row.unspoken_text_internal=unspoken;
  row.unspoken_word_count=words.length-heardWordCount;
  row.interrupted=true;
  row.interrupted_by=interrupter.id;
  row.interrupted_by_name=interrupter.name;
  row.interruption_reason=event.reason;
  row.interruption_reason_code=event.reasonCode;
  row.playback_ended_at=interruptedAt.toISOString();
  row.playback_started_at=playbackMs?new Date(interruptedAt.getTime()-playbackMs).toISOString():null;
  row.playback_skipped=true;
  row.audio_duration_ms=event.playbackMs;
  row.audio_file=null;
  c.awaitingPlayback=false;
  c.current=null;
  c.modelInterventions||=[];
  c.modelInterventions.push(event);
  c.forcedParticipantQueue=[interrupter.id,row.speaker_id];
  c.turnLimit=Math.min(40,Math.max(c.turnLimit,c.transcript.length+2));
  c.state=STATES.ACTIVE;
  return event;
}
export function beginTurn(c){if(c.awaitingPlayback)throw Error('Wait for playback completion');if(c.state===STATES.PAUSED)throw Error('Conversation is paused');if([STATES.COMPLETED,STATES.STOPPED,STATES.ERROR].includes(c.state))throw Error('Conversation has ended');c.state=STATES.ACTIVE;const participant=choose(c);c.current={participantId:participant.id,role:participant.role,turnIndex:c.transcript.length};return participant;}
export function recordTurn(c,turn){if(!c.current)throw Error('No turn is active');const p=c.participants.find(x=>x.id===c.current.participantId);const row={conversation_id:c.id,turn_id:randomUUID(),turn_index:c.transcript.length,speaker_id:p.id,speaker:p.name,role:p.role,model:p.model,voice:p.voice,timestamp:new Date().toISOString(),...turn};const event=(c.modelInterventions||[]).find(item=>!['completed','cancelled'].includes(item.state));if(event?.state==='pending_interrupter'&&event.interrupterId===p.id){row.autonomous_interruption=true;row.interruption_id=event.id;row.interruption_reason=event.reason;event.interruptionTurnId=row.turn_id;event.state='pending_reaction';}else if(event?.state==='pending_reaction'&&event.interruptedParticipantId===p.id){row.interruption_reaction=true;row.interruption_id=event.id;event.reactionTurnId=row.turn_id;event.state='completed';event.completedAt=new Date().toISOString();}c.transcript.push(row);if(c.forcedParticipantQueue?.[0]===p.id)c.forcedParticipantQueue.shift();const state=c.characterStates[p.id];state.claims.push(row.text);state.claims=state.claims.slice(-6);const addressed=new Set(row.addressed_intervention_ids||[]);for(const intervention of c.audienceInterventions||[]){if(!addressed.has(intervention.id)||!intervention.pendingParticipantIds?.includes(p.id))continue;intervention.pendingParticipantIds=intervention.pendingParticipantIds.filter(id=>id!==p.id);intervention.acknowledgedBy=[...(intervention.acknowledgedBy||[]),{participantId:p.id,turnId:row.turn_id}];}c.awaitingPlayback=true;return row;}
export function completePlayback(c,{durationMs=null,skipped=false}={}){if(!c.awaitingPlayback)throw Error('No playback is awaiting completion');const row=c.transcript.at(-1);const endedAt=new Date();row.audio_duration_ms=durationMs;row.playback_skipped=Boolean(skipped);row.playback_ended_at=endedAt.toISOString();row.playback_started_at=Number(durationMs)>0?new Date(endedAt.getTime()-Number(durationMs)).toISOString():null;c.awaitingPlayback=false;c.current=null;const pending=(c.audienceInterventions||[]).some(item=>item.pendingParticipantIds?.length);c.state=c.transcript.length>=c.turnLimit&&!pending?STATES.COMPLETED:STATES.ACTIVE;return c;}
export function pause(c){if(c.state!==STATES.ACTIVE)throw Error('Conversation is not active');c.resumeState=c.state;c.state=STATES.PAUSED;return c;}export function resume(c){if(c.state!==STATES.PAUSED)throw Error('Conversation is not paused');c.state=c.resumeState||STATES.ACTIVE;c.resumeState=null;return c;}export function stop(c){c.awaitingPlayback=false;c.current=null;c.state=STATES.STOPPED;return c;}
