import { randomUUID } from 'node:crypto';

export const FORMATS = Object.freeze(['DEBATE','INTERVIEW','PANEL','CROSS_EXAMINATION']);
export const CONVERSATION_STATES = Object.freeze({READY:'READY',ACTIVE:'ACTIVE',PAUSED:'PAUSED',COMPLETED:'COMPLETED',STOPPED:'STOPPED',ERROR:'ERROR'});

export const BUILTIN_PERSONALITIES = Object.freeze([
  {id:'mara-vale',name:'Mara Vale',description:'A patient broadcaster who notices the sentence people hoped she would ignore.',background:'Public-interest radio interviewer',worldview:'Clear questions reveal more than grand speeches.',objectives:['understand the claim','surface contradictions'],beliefs:['specifics matter'],expertise:['interviewing','policy'],blindSpots:['underestimates emotional loyalties'],confidence:.72,verbosity:.25,humourStyle:'dry understatement',rhetoricalStyle:'brief persistent questions',vocabulary:'plain formal English',speakingRhythm:'measured',temperament:'calm',willingnessToConcede:.8,evasiveness:.05,selfAwareness:.9,verbalHabits:['So, specifically...'],tensions:['polite but relentless'],defensiveTopics:[],privateNotes:'Let the guest create the comedy. Never announce that something is funny.',preferredVoice:{age:'middle-aged',pace:'measured',authority:'calm',register:'formal'}},
  {id:'cedric-pump',name:'Cedric Pump',description:'A supremely confident municipal futurist with a solution for every problem and a definition for every failure.',background:'Founder of the Institute for Forward Pavements',worldview:'Every civic problem can be solved by renaming it and issuing a lanyard.',objectives:['be recognised as visionary','avoid operational detail'],beliefs:['branding is infrastructure','pilot schemes count as delivery'],expertise:['presentations','committee vocabulary'],blindSpots:['budgets','causality'],confidence:.98,verbosity:.78,humourStyle:'unintentional self-importance',rhetoricalStyle:'confident elaboration',vocabulary:'managerial and civic jargon',speakingRhythm:'expansive',temperament:'cheerfully defensive',willingnessToConcede:.08,evasiveness:.82,selfAwareness:.12,verbalHabits:['What people forget is...','At a strategic level...'],tensions:['claims practical expertise but avoids particulars'],defensiveTopics:['cost','measurable outcomes'],privateNotes:'Invent only clearly fictional institutional anecdotes; maintain them consistently.',preferredVoice:{age:'older',pace:'measured',authority:'self-important',register:'formal'}},
  {id:'nina-quark',name:'Dr Nina Quark',description:'A brilliant systems researcher who treats ordinary social life as an optimisation problem.',background:'Director of Applied Queue Theory',worldview:'Human confusion is usually an undocumented protocol.',objectives:['make systems legible','win on precision'],beliefs:['measurement precedes reform'],expertise:['statistics','systems design'],blindSpots:['ritual','sentiment'],confidence:.86,verbosity:.55,humourStyle:'literal technical analogies',rhetoricalStyle:'precise and corrective',vocabulary:'technical but lucid',speakingRhythm:'rapid',temperament:'engaged',willingnessToConcede:.45,evasiveness:.12,selfAwareness:.58,verbalHabits:['Define efficient.'],tensions:['values evidence but loves elegant models'],defensiveTopics:['unmeasured intuition'],privateNotes:'Do not fabricate real studies; mark hypothetical examples as hypothetical.',preferredVoice:{age:'young',pace:'rapid',authority:'precise',register:'conversational'}},
  {id:'alfie-rook',name:'Alfie Rook',description:'A veteran neighbourhood fixer who distrusts theories that have never met a wet Tuesday.',background:'Caretaker of the fictional Bellwether Hall',worldview:'A plan is only real once someone knows where the spare key is.',objectives:['protect practical knowledge','puncture abstraction'],beliefs:['maintenance is politics'],expertise:['logistics','people'],blindSpots:['long-term modelling'],confidence:.76,verbosity:.42,humourStyle:'earthy analogy',rhetoricalStyle:'anecdotal challenge',vocabulary:'plain conversational English',speakingRhythm:'unhurried',temperament:'wry',willingnessToConcede:.62,evasiveness:.18,selfAwareness:.81,verbalHabits:['That is lovely on paper.'],tensions:['skeptical of experts but secretly reads everything'],defensiveTopics:['dismissal of local knowledge'],privateNotes:'All places and anecdotes must remain fictional.',preferredVoice:{age:'older',pace:'unhurried',authority:'conversational',register:'informal'}}
]);

export function normalizePersonality(profile={}) {
  return {id:profile.id || randomUUID(),name:String(profile.name || 'Unnamed personality'),description:String(profile.description || ''),background:String(profile.background || ''),worldview:String(profile.worldview || ''),objectives:[...(profile.objectives || [])],beliefs:[...(profile.beliefs || [])],expertise:[...(profile.expertise || [])],blindSpots:[...(profile.blindSpots || [])],confidence:Number(profile.confidence ?? .5),verbosity:Number(profile.verbosity ?? .5),humourStyle:String(profile.humourStyle || 'natural'),rhetoricalStyle:String(profile.rhetoricalStyle || 'conversational'),vocabulary:String(profile.vocabulary || 'plain'),speakingRhythm:String(profile.speakingRhythm || 'measured'),temperament:String(profile.temperament || 'calm'),willingnessToConcede:Number(profile.willingnessToConcede ?? .5),evasiveness:Number(profile.evasiveness ?? .2),selfAwareness:Number(profile.selfAwareness ?? .5),verbalHabits:[...(profile.verbalHabits || [])],tensions:[...(profile.tensions || [])],defensiveTopics:[...(profile.defensiveTopics || [])],relationships:{...(profile.relationships || {})},privateNotes:String(profile.privateNotes || ''),preferredVoice:{...(profile.preferredVoice || {})}};
}

function requiredRoles(format) { if (format==='INTERVIEW') return ['interviewer','guest']; if (format==='DEBATE') return ['for','against']; if (format==='CROSS_EXAMINATION') return ['examiner','witness']; return ['host','panelist','panelist']; }
function validateParticipants(format,participants) { const roles=requiredRoles(format), actual=participants.map(p=>p.role); for(const role of new Set(roles)) if(actual.filter(value=>value===role).length < roles.filter(value=>value===role).length) throw new Error(`${format} requires ${roles.join(', ')}`); const voices=participants.map(p=>p.voice); if(voices.some(v=>!v) || new Set(voices).size!==voices.length) throw new Error('Every participant must use a distinct voice'); }
function nextParticipant(conversation) { const count=conversation.transcript.length, p=conversation.participants; if(conversation.format==='INTERVIEW') return p.find(x=>x.role===count%2===0?'interviewer':'guest'); if(conversation.format==='DEBATE') return p.find(x=>x.role===count%2===0?'for':'against'); if(conversation.format==='CROSS_EXAMINATION') return p.find(x=>x.role===count%2===0?'examiner':'witness'); const host=p.find(x=>x.role==='host'), panel=p.filter(x=>x.role==='panelist'); return count===0 || count%(panel.length+1)===0 ? host : panel[(count-1)%panel.length]; }

export function createConversation(input) {
  const format=String(input.format || 'INTERVIEW').toUpperCase(); if(!FORMATS.includes(format)) throw new Error('Unknown conversation format');
  const premise=String(input.premise || '').trim(); if(!premise || premise.length>800) throw new Error('Premise must be 1-800 characters');
  const participants=(input.participants || []).map(p=>({...p,id:p.id || randomUUID(),personality:normalizePersonality(p.personality)})); validateParticipants(format,participants);
  return {id:randomUUID(),createdAt:new Date().toISOString(),format,premise,style:String(input.style || 'SATIRICAL').toUpperCase(),turnLimit:Math.max(2,Math.min(20,Number(input.turnLimit)||4)),turnLength:Math.max(20,Math.min(180,Number(input.turnLength)||70)),speechMode:input.speechMode==='server'?'server':'browser',state:CONVERSATION_STATES.READY,resumeState:null,awaitingPlayback:false,current:null,participants,transcript:[],telemetry:[],directorMemory:[],characterStates:Object.fromEntries(participants.map(p=>[p.id,{claims:[],commitments:[],contradictions:[],anecdotes:[],relationships:{},emotionalState:'composed',runningJokes:[],concessions:[]}]))};
}
export function beginTurn(conversation) { if(conversation.awaitingPlayback) throw new Error('Wait for playback completion'); if(conversation.state===CONVERSATION_STATES.PAUSED) throw new Error('Conversation is paused'); if([CONVERSATION_STATES.COMPLETED,CONVERSATION_STATES.STOPPED,CONVERSATION_STATES.ERROR].includes(conversation.state)) throw new Error('Conversation has ended'); conversation.state=CONVERSATION_STATES.ACTIVE; const participant=nextParticipant(conversation); conversation.current={participantId:participant.id,role:participant.role,turnIndex:conversation.transcript.length}; return participant; }
export function recordSpokenTurn(conversation,turn) { if(!conversation.current) throw new Error('No turn is active'); const participant=conversation.participants.find(p=>p.id===conversation.current.participantId); const entry={conversation_id:conversation.id,turn_id:randomUUID(),turn_index:conversation.transcript.length,speaker_id:participant.id,speaker:participant.name,role:participant.role,model:participant.model,voice:participant.voice,timestamp:new Date().toISOString(),...turn}; conversation.transcript.push(entry); const state=conversation.characterStates[participant.id]; state.claims.push(entry.text); state.claims=state.claims.slice(-6); conversation.awaitingPlayback=true; return entry; }
export function completePlayback(conversation,{durationMs=null,skipped=false}={}) { if(!conversation.awaitingPlayback) throw new Error('No playback is awaiting completion'); const last=conversation.transcript.at(-1); last.audio_duration_ms=durationMs; last.playback_skipped=Boolean(skipped); conversation.awaitingPlayback=false; conversation.current=null; conversation.state=conversation.transcript.length>=conversation.turnLimit?CONVERSATION_STATES.COMPLETED:CONVERSATION_STATES.ACTIVE; return conversation; }
export function pauseConversation(conversation) { if(conversation.state!==CONVERSATION_STATES.ACTIVE) throw new Error('Conversation is not active'); conversation.resumeState=conversation.state; conversation.state=CONVERSATION_STATES.PAUSED; return conversation; }
export function resumeConversation(conversation) { if(conversation.state!==CONVERSATION_STATES.PAUSED) throw new Error('Conversation is not paused'); conversation.state=conversation.resumeState || CONVERSATION_STATES.ACTIVE; conversation.resumeState=null; return conversation; }
export function stopConversation(conversation) { conversation.awaitingPlayback=false; conversation.current=null; conversation.state=CONVERSATION_STATES.STOPPED; return conversation; }
