import { randomUUID } from 'node:crypto';

export const FORMATS=['DEBATE','INTERVIEW','PANEL','CROSS_EXAMINATION'];
export const STATES={READY:'READY',ACTIVE:'ACTIVE',PAUSED:'PAUSED',COMPLETED:'COMPLETED',STOPPED:'STOPPED',ERROR:'ERROR'};
export const PERSONALITIES=[
  {id:'mara-vale',name:'Mara Vale',description:'A patient broadcaster who notices the sentence people hoped she would ignore.',background:'Public-interest radio interviewer',worldview:'Clear questions reveal more than grand speeches.',objectives:['understand the claim','surface contradictions'],beliefs:['specifics matter'],expertise:['interviewing','policy'],blindSpots:['underestimates emotional loyalties'],confidence:.72,verbosity:.25,humourStyle:'dry understatement',rhetoricalStyle:'brief persistent questions',vocabulary:'plain formal English',speakingRhythm:'measured',temperament:'calm',willingnessToConcede:.8,evasiveness:.05,selfAwareness:.9,verbalHabits:['So, specifically...'],tensions:['polite but relentless'],defensiveTopics:[],privateNotes:'Let the guest create the comedy. Never announce that something is funny.',preferredVoice:{age:'middle-aged',pace:'measured',authority:'calm',register:'formal'}},
  {id:'cedric-pump',name:'Cedric Pump',description:'A supremely confident municipal futurist with a solution for every problem and a definition for every failure.',background:'Founder of the fictional Institute for Forward Pavements',worldview:'Every civic problem can be solved by renaming it and issuing a lanyard.',objectives:['be recognised as visionary','avoid operational detail'],beliefs:['branding is infrastructure','pilot schemes count as delivery'],expertise:['presentations','committee vocabulary'],blindSpots:['budgets','causality'],confidence:.98,verbosity:.78,humourStyle:'unintentional self-importance',rhetoricalStyle:'confident elaboration',vocabulary:'managerial civic jargon',speakingRhythm:'expansive',temperament:'cheerfully defensive',willingnessToConcede:.08,evasiveness:.82,selfAwareness:.12,verbalHabits:['What people forget is...','At a strategic level...'],tensions:['claims practical expertise but avoids particulars'],defensiveTopics:['cost','measurable outcomes'],privateNotes:'Maintain fictional anecdotes consistently. Never reference or imitate a real comic character.',preferredVoice:{age:'older',pace:'measured',authority:'self-important',register:'formal'}},
  {id:'nina-quark',name:'Dr Nina Quark',description:'A systems researcher who treats ordinary social life as an optimisation problem.',background:'Director of Applied Queue Theory',worldview:'Human confusion is usually an undocumented protocol.',objectives:['make systems legible','win on precision'],beliefs:['measurement precedes reform'],expertise:['statistics','systems design'],blindSpots:['ritual','sentiment'],confidence:.86,verbosity:.55,humourStyle:'literal technical analogies',rhetoricalStyle:'precise and corrective',vocabulary:'technical but lucid',speakingRhythm:'rapid',temperament:'engaged',willingnessToConcede:.45,evasiveness:.12,selfAwareness:.58,verbalHabits:['Define efficient.'],tensions:['values evidence but loves elegant models'],defensiveTopics:['unmeasured intuition'],privateNotes:'Do not fabricate real studies.',preferredVoice:{age:'young',pace:'rapid',authority:'precise',register:'conversational'}},
  {id:'alfie-rook',name:'Alfie Rook',description:'A veteran neighbourhood fixer who distrusts theories that have never met a wet Tuesday.',background:'Caretaker of the fictional Bellwether Hall',worldview:'A plan is only real once someone knows where the spare key is.',objectives:['protect practical knowledge','puncture abstraction'],beliefs:['maintenance is politics'],expertise:['logistics','people'],blindSpots:['long-term modelling'],confidence:.76,verbosity:.42,humourStyle:'earthy analogy',rhetoricalStyle:'anecdotal challenge',vocabulary:'plain conversational English',speakingRhythm:'unhurried',temperament:'wry',willingnessToConcede:.62,evasiveness:.18,selfAwareness:.81,verbalHabits:['That is lovely on paper.'],tensions:['skeptical of experts but secretly reads everything'],defensiveTopics:['dismissal of local knowledge'],privateNotes:'All anecdotes remain fictional.',preferredVoice:{age:'older',pace:'unhurried',authority:'conversational',register:'informal'}}
];

export function normalizePersonality(p={}) { return {id:p.id||randomUUID(),name:String(p.name||'Unnamed personality'),description:String(p.description||''),background:String(p.background||''),worldview:String(p.worldview||''),objectives:[...(p.objectives||[])],beliefs:[...(p.beliefs||[])],expertise:[...(p.expertise||[])],blindSpots:[...(p.blindSpots||[])],confidence:Number(p.confidence??.5),verbosity:Number(p.verbosity??.5),humourStyle:String(p.humourStyle||'natural'),rhetoricalStyle:String(p.rhetoricalStyle||'conversational'),vocabulary:String(p.vocabulary||'plain'),speakingRhythm:String(p.speakingRhythm||'measured'),temperament:String(p.temperament||'calm'),willingnessToConcede:Number(p.willingnessToConcede??.5),evasiveness:Number(p.evasiveness??.2),selfAwareness:Number(p.selfAwareness??.5),verbalHabits:[...(p.verbalHabits||[])],tensions:[...(p.tensions||[])],defensiveTopics:[...(p.defensiveTopics||[])],relationships:{...(p.relationships||{})},privateNotes:String(p.privateNotes||''),preferredVoice:{...(p.preferredVoice||{})}}; }
function roleList(format){return format==='INTERVIEW'?['interviewer','guest']:format==='DEBATE'?['for','against']:format==='CROSS_EXAMINATION'?['examiner','witness']:['host','panelist','panelist'];}
function validate(format,participants){for(const role of new Set(roleList(format))){const needed=roleList(format).filter(x=>x===role).length;if(participants.filter(x=>x.role===role).length<needed)throw Error(`${format} requires ${roleList(format).join(', ')}`);}const voices=participants.map(x=>x.voice);if(voices.some(x=>!x)||new Set(voices).size!==voices.length)throw Error('Every participant must use a distinct voice');}
function choose(c){const n=c.transcript.length,p=c.participants;if(c.format==='INTERVIEW')return p.find(x=>x.role===(n%2===0?'interviewer':'guest'));if(c.format==='DEBATE')return p.find(x=>x.role===(n%2===0?'for':'against'));if(c.format==='CROSS_EXAMINATION')return p.find(x=>x.role===(n%2===0?'examiner':'witness'));const host=p.find(x=>x.role==='host'),panel=p.filter(x=>x.role==='panelist');return n===0||n%(panel.length+1)===0?host:panel[(n-1)%panel.length];}
export function createConversation(input){const format=String(input.format||'INTERVIEW').toUpperCase();if(!FORMATS.includes(format))throw Error('Unknown conversation format');const premise=String(input.premise||'').trim();if(!premise||premise.length>800)throw Error('Premise must be 1-800 characters');const participants=(input.participants||[]).map(p=>({...p,id:p.id||randomUUID(),personality:normalizePersonality(p.personality)}));validate(format,participants);return{id:randomUUID(),createdAt:new Date().toISOString(),format,premise,style:String(input.style||'SATIRICAL').toUpperCase(),turnLimit:Math.max(2,Math.min(20,Number(input.turnLimit)||4)),turnLength:Math.max(20,Math.min(180,Number(input.turnLength)||60)),speechMode:input.speechMode==='server'?'server':'browser',state:STATES.READY,resumeState:null,awaitingPlayback:false,current:null,participants,transcript:[],telemetry:[],directorMemory:[],characterStates:Object.fromEntries(participants.map(p=>[p.id,{claims:[],commitments:[],contradictions:[],anecdotes:[],relationships:{},emotionalState:'composed',runningJokes:[],concessions:[]}]))};}
export function beginTurn(c){if(c.awaitingPlayback)throw Error('Wait for playback completion');if(c.state===STATES.PAUSED)throw Error('Conversation is paused');if([STATES.COMPLETED,STATES.STOPPED,STATES.ERROR].includes(c.state))throw Error('Conversation has ended');c.state=STATES.ACTIVE;const participant=choose(c);c.current={participantId:participant.id,role:participant.role,turnIndex:c.transcript.length};return participant;}
export function recordTurn(c,turn){if(!c.current)throw Error('No turn is active');const p=c.participants.find(x=>x.id===c.current.participantId);const row={conversation_id:c.id,turn_id:randomUUID(),turn_index:c.transcript.length,speaker_id:p.id,speaker:p.name,role:p.role,model:p.model,voice:p.voice,timestamp:new Date().toISOString(),...turn};c.transcript.push(row);const state=c.characterStates[p.id];state.claims.push(row.text);state.claims=state.claims.slice(-6);c.awaitingPlayback=true;return row;}
export function completePlayback(c,{durationMs=null,skipped=false}={}){if(!c.awaitingPlayback)throw Error('No playback is awaiting completion');const row=c.transcript.at(-1);row.audio_duration_ms=durationMs;row.playback_skipped=Boolean(skipped);c.awaitingPlayback=false;c.current=null;c.state=c.transcript.length>=c.turnLimit?STATES.COMPLETED:STATES.ACTIVE;return c;}
export function pause(c){if(c.state!==STATES.ACTIVE)throw Error('Conversation is not active');c.resumeState=c.state;c.state=STATES.PAUSED;return c;}export function resume(c){if(c.state!==STATES.PAUSED)throw Error('Conversation is not paused');c.state=c.resumeState||STATES.ACTIVE;c.resumeState=null;return c;}export function stop(c){c.awaitingPlayback=false;c.current=null;c.state=STATES.STOPPED;return c;}
